### PR TITLE
Restore AndroidManifest.xml 

### PR DESCRIPTION
**Pull request by duswnchl**
AndroidManifest.xml for chromium will be imported from libraries.

### CODE REVIEW

**Comment by duswnchl** [comment]
Related PR in igalia/wolvic-chromium : https://github.com/Igalia/wolvic-chromium/pull/3

**Review by zakharvoit — APPROVED** [review]
LGTM

**Comment by mshin-wolvic** [comment]
LGTM

**Review by mshin-wolvic — APPROVED** [review]

**Comment by svillar** [comment]
Mind rebasing this on top of the current main? It has some conflicts and it's also based on code that is already part of the main branch (like all the backend flavour code)

**Review by svillar — CHANGES_REQUESTED** [review]
Basically asking for a rebase before reviewing

**Comment by duswnchl** [comment]
> Mind rebasing this on top of the current main? It has some conflicts and it's also based on code that is already part of the main branch (like all the backend flavour code)

Sorry for the inconvenience. Done!

**Pull request merged**
