### PR TITLE
Adjust skybox textures' file type and format

### PR DESCRIPTION
**Pull request by felipeerias**
Use compressed KTX textures for the skybox in all systems except Pico versions below 5.4.0.

Those textures are displayed using the format GL_COMPRESSED_SRGB8_ETC2.

For Pico versions below 5.4.0, the skybox textures are PNG files displayed with the GL_SRGB8_ALPHA8 format.

This is a partial fix for issue #522, as we will still keep the Pico PNG files around for some time.

### CODE REVIEW

**Review by svillar — CHANGES_REQUESTED** [review]
This is great, however we first need some PR that disables running Wolvic in PicoOS<5.4 (and also removes the current other  workarounds we have for that). Then we could land this.

**Review by svillar — CHANGES_REQUESTED** [review]
So knowing the good percentage of Pico4 users running older versions of the OS, I guess it's safer to keep the workaround and only enable compressed textures for >=5.4

**Comment by svillar** [comment]
The problem here is the brightness of the cubemap. I though it was because you're using SRGB instead of RGB but after changing that I don't see any significant change. There were some other parts of the code in which we need to disable some OpenGL extension in order not to get too "bright" colors, I think you should check that.

**Comment by felipeerias** [comment]
I have been investigating the problems with the skybox colors.

As far as I understand, the issue is that there is a configuration problem with the skybox textures/layers which means that the colors are not properly processed and look too bright.

Our texture files use two formats:

- RGB textures use `GL_COMPRESSED_RGB8_ETC2`
- sRGB textures (`*_srgb.ktx`) use `GL_COMPRESSED_SRGB8_ETC2`

Both of these formats should be supported in Pico (they are included in the output of `xrEnumerateSwapchainFormats()`). Using either RGB or sRGB textures appears to have exactly the same (wrong) outcome.

There was a similar issue with the splash screen that was solved  by disabling the [`GL_FRAMEBUFFER_SRGB_EXT`](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_framebuffer_sRGB.txt) extension. This extension makes framebuffers assume that drawable elements are "encoded for the sRGB color space and hence need to be linearized".

The skybox issue looks similar to what would happen after that RGB→sRGB conversion, however I haven't been able to find the point where this is being done.

**Comment by svillar** [comment]
Let's close this and retake it later if needed

**Pull request closed without merging**
