### PR TITLE
Copy search engine list from upstream and add yandex when Russian

### LINKED ISSUE #922: Add Yandex to the list of available search engines
**Is your feature request related to a problem? Please describe.**
Currently Wolvic doesn't support Yandex as one of the options we offer the users to select as default search engine

**Describe the solution you'd like**
Include Yandex as one of the options to select the default search engine

**Describe alternatives you've considered**
It's possible to use the search engine through the yandex.com site

### PR DESCRIPTION
**Pull request by HollowMan6**
This should of course be done upstream, but considering that the change won't get into Wolvic until they release and we upgrade the Android Component version, let's just make a copy of that from upstream and do our customization locally.

Resolves #922

### CODE REVIEW

**Comment by HollowMan6** [comment]
Copied from https://github.com/mozilla-mobile/firefox-android/blob/2bbf674006c9f3b093a400e0025eac409ce784fe/android-components/components/feature/search/src/main/assets/search/list.json

**Comment by HollowMan6** [comment]
Some latest updates: https://github.com/Igalia/wolvic/issues/922#issuecomment-1688337850

**Comment by svillar** [comment]
> Some latest updates: [#922 (comment)](https://github.com/Igalia/wolvic/issues/922#issuecomment-1688337850)

Not a fan of duplicating the list "locally". Also what you mention ^^^ seems relevant so we should probably stick to the list from AC.

**Comment by HollowMan6** [comment]
Okay! Closing this and that issue.

**Pull request closed without merging**
