### PR TITLE
New file with general purpose utils

### LINKED ISSUE #457: Refactor some utility functions/macros
Some of the methods and macros in `OpenXRHelpers.h` and `BrowserWorld` should be refactored to some other file with utilities. In the `OpenXRHelpers` case some of them are not even OpenXR related, like `ASSERT()`

### PR DESCRIPTION
**Pull request by javifernandez**
It d be useful to have a general purpose utils file with macros and functions for common logic along the project. For now there a a few macros for stringify and logging use cases, but we may add more in the future.

The PR also applies some refactoring on the files already  using these macros. 

Fixes #457

### CODE REVIEW

**Review by svillar — CHANGES_REQUESTED** [review]
I think the main objection I have is that GeneralUtils is too abstract. I think we should call this `Assertions.h` for example and place there all the code that you're moving, including the `ASSERT_ON_RENDER_THREAD`. No te that the string macros are basically there to implement the assertion checks.

**Comment by javifernandez** [comment]
Thanks for the review Sergio; I knew the name was going to be one of the biggest challenges :P In previous versions of the patch I tried to add macros like ENUM_CASE_STR and MAKE_TO_STRING_FUNC that are used to define 'to_string' functions, so that's why I decided to go with a generic name. 

I agree that Assertion.h is a good name for now. However, I had some doubts about  ASSERT_ON_RENDER_THREAD, which I removed in the last minute. it uses the 'm' State() attribute of the BrowserWorld class, so it's tied to that file.

**Comment by svillar** [comment]
> Thanks for the review Sergio; I knew the name was going to be one of the biggest challenges :P In previous versions of the patch I tried to add macros like ENUM_CASE_STR and MAKE_TO_STRING_FUNC that are used to define 'to_string' functions, so that's why I decided to go with a generic name.
> 
> I agree that Assertion.h is a good name for now. However, I had some doubts about ASSERT_ON_RENDER_THREAD, which I removed in the last minute. it uses the 'm' State() attribute of the BrowserWorld class, so it's tied to that file.

Yeah, perhaps even passing the context directly to the macro does not make much sense because it would make it so specific that nobody else will use it. So I'm fine keeping it in `BrowserWorld` but let's rename the file anyway

**Review by svillar — CHANGES_REQUESTED** [review]

**Review by svillar — APPROVED** [review]
Nice thanks

**Pull request merged**
