### PR TITLE
[OpenXR] Workaround phantom click events with hand interaction

### PR DESCRIPTION
**Pull request by svillar**
This PR tries to workaround the phantom clicks we get from the MagicLeap OpenXR runtime when moving the hands out of sight and using the hand interaction profile.

First of all it reverts the previous attempt to solve this as it was not working fine. Then it implements a new solution based on gesture detection. We now require a detection of the gesture of the hands facing the head from the hand joints data.

### CODE REVIEW

**Review by javifernandez — APPROVED** [review]
The change looks good and I've already tried and solves most of the cases. 

However, do the 3 commits make sense now ? Haven't you reverted the workaround in the last commit ?

**Comment by svillar** [comment]
> The change looks good and I've already tried and solves most of the cases.
> 
> However, do the 3 commits make sense now ? Haven't you reverted the workaround in the last commit ?

The first commit is the revert. The 2nd is the fix and the 3rd is a nice followup which I agree is kind of unrelated, but I found it while developing this one.

**Comment by javifernandez** [comment]
> > The change looks good and I've already tried and solves most of the cases.
> > However, do the 3 commits make sense now ? Haven't you reverted the workaround in the last commit ?
> 
> The first commit is the revert. The 2nd is the fix and the 3rd is a nice followup which I agree is kind of unrelated, but I found it while developing this one.

But my question is whether we should squash them, at least the revert.

**Comment by svillar** [comment]
> > > The change looks good and I've already tried and solves most of the cases.
> > > However, do the 3 commits make sense now ? Haven't you reverted the workaround in the last commit ?
> > 
> > 
> > The first commit is the revert. The 2nd is the fix and the 3rd is a nice followup which I agree is kind of unrelated, but I found it while developing this one.
> 
> But my question is whether we should squash them, at least the revert.

Oh I think it's good to have them as separate commits. It's cleaner from the history POV

**Pull request merged**
