### PR TITLE
  [VisionGlass] Style phone UI

### PR DESCRIPTION
**Pull request by felipeerias**
This PR contains several changes to the Vision Glass UI on the phone:

- rename Vision Glass app to "Wolvic Vision";
- use a dark icon to distinguish this version of Wolvic from the HVR one, which might be installed at the same time;
- set the phone UI theme and style the UI elements, without changes in functionality;
- don't force the Vision Glass app to be fullscreen.

### CODE REVIEW

**Comment by felipeerias** [comment]
Updated icon and name:

Screenshot_20240228_151551

**Comment by felipeerias** [comment]
Updated phone UI:

Screenshot_20240228_151551
Screenshot_20240228_151606

**Review by svillar — CHANGES_REQUESTED** [review]
Great Visual improvement indeed.

A couple of things:
1. The new icon is not shown to me in debug builds
2. The app crashes whenever the media controls are about to be shown
```
java.lang.ClassCastException: com.google.android.material.button.MaterialButton cannot be cast to android.widget.ImageButton
                                                  	at com.igalia.wolvic.PlatformActivity$PlatformActivityPluginVisionGlass$1.onPlay(PlatformActivity.java:434)
                                                  	at com.igalia.wolvic.browser.Media.lambda$onPlay$4(Media.java:186)
                                                  	at com.igalia.wolvic.browser.Media$$ExternalSyntheticLambda4.accept(Unknown Source:6)
                                                  	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:832)
                                                  	at com.igalia.wolvic.browser.Media.onPlay(Media.java:186)
                                                  	at com.igalia.wolvic.browser.api.impl.MediaSessionDelegateImpl.onPlay(MediaSessionDelegateImpl.java:53)
                                                  	at org.mozilla.geckoview.MediaSession$Handler.handleMessage(MediaSession.java:626)
                                                  	at org.mozilla.geckoview.MediaSession$Handler.handleMessage(MediaSession.java:575)
                                                  	at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:88)
                                                  	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:426)
                                                  	at android.os.Handler.handleCallback(Handler.java:966)
                                                  	at android.os.Handler.dispatchMessage(Handler.java:110)
                                                  	at android.os.Looper.loopOnce(Looper.java:205)
                                                  	at android.os.Looper.loop(Looper.java:293)
                                                  	at android.app.ActivityThread.loopProcess(ActivityThread.java:9934)
                                                  	at android.app.ActivityThread.main(ActivityThread.java:9923)
                                                  	at java.lang.reflect.Method.invoke(Native Method)
                                                  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
                                                  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)
```

**Review by svillar — APPROVED** [review]
I am not going to block this because the overall appearance is much better but I have a suggestion for a follow up patch. In the media controls bar I intentionally left a blank space so that the play/pause button was centered on screen. I still think that's a good idea. I know that we have an even number of buttons (not ideal) but in all the UIs I know the play button is always centered.

**Pull request merged**
