### PR TITLE
Always bypass cache for some specific urls

### LINKED ISSUE #353: Download dialog cannot show repeatedly
## Configuration

Wolvic version:  any
Wolvic build ID: any

Hardware:  any

## Steps to Reproduce

1. load https://privacy.qq.com/document/priview/2491347092a64d7fa00cbc2bf68fbbbb
2. click the top-right button "下载" on the web page。
3. close the download dialog and the blank tab, then click the “下载” button again 

## Current Behavior

1. After the first click，the download dialog can show，but after the second click，the dialog cannot show expectedly
2. After the first click, onNewSession, onPageStart, onExternalResponse, and onPageStop are called. But after the second click, only onNewSession and onPageStart are called, no onExternalResponse and onPageStop. As a result the new blank tab is always loading. The download dialog can show again until restart Wolvic

image

## Expected Behavior

With repeated button clicks, the download dialog shows repeatedly.

## Error Logs and Stack Traces

<details open>

```
```

</details>

### PR DESCRIPTION
**Pull request by HollowMan6**
Resolve #353 and #1097

### CODE REVIEW

**Review by svillar — CHANGES_REQUESTED** [review]
I don't think we should follow this path even if it's a temporary measure. We should go deeper in the reasons why this is happening.

**Comment by HollowMan6** [comment]
> I don't think we should follow this path even if it's a temporary measure. We should go deeper in the reasons why this is happening.

Not sure at all what caused this, can't spot anything weird when debugging. @svillar Can you check with the Chromium backend to see if we have the same cache issue there?

I'm now starting to doubt if this is because we handle the gecko session differently than Fenix (Firefox for Android). I started to notice the difference between Wolvic and Fenix when I worked on the find in page feature https://github.com/Igalia/wolvic/issues/929#issuecomment-1688666846 (Fenix heavily depends on browserStore and [EngineView](https://github.com/mozilla-mobile/firefox-android/blob/main/android-components/components/feature/session/README.md), while we use another way (traditional way? for easy integration of another browser backend?) to interact with the session) I even start to think that the issue here https://github.com/Igalia/wolvic/pull/1046#issuecomment-1749607840 is caused by our way of interacting with the gecko session, too. All those issues are not reproducible in Firefox for Android at all.

**Comment by svillar** [comment]
> > I don't think we should follow this path even if it's a temporary measure. We should go deeper in the reasons why this is happening.
> 
> Not sure at all what caused this, can't spot anything weird when debugging. @svillar Can you check with the Chromium backend to see if we have the same cache issue there?

Cannot reproduce it with chromium backend (although right now I cannot reproduce it with 1.5.1 either)
 
> I'm now starting to doubt if this is because we handle the gecko session differently than Fenix (Firefox for Android). I started to notice the difference between Wolvic and Fenix when I worked on the find in page feature [#929 (comment)](https://github.com/Igalia/wolvic/issues/929#issuecomment-1688666846) (Fenix heavily depends on browserStore and [EngineView](https://github.com/mozilla-mobile/firefox-android/blob/main/android-components/components/feature/session/README.md), while we use another way (traditional way? for easy integration of another browser backend?) to interact with the session) I even start to think that the issue here [#1046 (comment)](https://github.com/Igalia/wolvic/pull/1046#issuecomment-1749607840) is caused by our way of interacting with the gecko session, too. All those issues are not reproducible in Firefox for Android at all.

Yeah that's one of the things I realized after joining the project. We use lower level APIs. I guess by the time FxR was born the only available API was the GeckoView interface. Then Mozilla built some other components on top. I was also researching about that when I had to debug the dozens of media playback issues we've had in the past (some of them are still here or require hacks in gecko)

**Comment by HollowMan6** [comment]
Okay, I guess later, if we find those higher-level APIs still compatible to integrate with another backend (i.e Chromium), we can consider refactoring our codebase and moving everything there. This can be a root fix as I guess Gecko may not expect people to use these lower-level APIs now, so they can be very buggy (e.g. caches didn't get cleared correctly when reloading / all media sessions' sound gets muted when we close a tab) if we continue using them. It can hopefully fix at least the following issues:
- https://github.com/Igalia/wolvic/issues/1097
- https://github.com/Igalia/wolvic/issues/353
- https://github.com/Igalia/wolvic/issues/598
- https://github.com/Igalia/wolvic/issues/87
- https://github.com/Igalia/wolvic/issues/86 (Probably related to this as well)

@svillar If you agree with this, I can open a separate issue for tracking the investigation.

**Comment by svillar** [comment]
> @svillar If you agree with this, I can open a separate issue for tracking the investigation.

Yeah I think we can spend some time researching about the possibilities after that we could decide whether we want to follow that path or focus on other interesting pending tasks related to the UI revamp

**Comment by svillar** [comment]
I don't think we'll land something like this, so perhaps it's better to close it...

**Comment by HollowMan6** [comment]
Opened issue #1121 now, so this can be closed.

**Pull request closed without merging**
