### PR TITLE
Support min and max values on Time Picker

### LINKED ISSUE #1259: Support `min` and `max` values on Time Picker
Support `min` and `max`  attributes in <input type="time|datetime-local"> on Time picker

HTML Spec : https://html.spec.whatwg.org/multipage/input.html#the-min-and-max-attributes

### PR DESCRIPTION
**Pull request by HoussemNasri**
Closes #1259

## TODO

- [ ] ~~Write unit tests for RangeTimePickerWidget~~
- [ ] ~~Add a video demo to the PR description~~

### CODE REVIEW

**Comment by svillar** [comment]
Is this ready for review or?

**Comment by HoussemNasri** [comment]
I want to experiment with testing a bit, unfortunately, I couldn't allocate time for it, if I can't do it this week I'll mark it as ready for review.

**Comment by svillar** [comment]
Converting to draft while it's still WIP

**Comment by HoussemNasri** [comment]
I can't allocate time to continue working on this in the near future so I'm closing it.

**Pull request closed without merging**
