### PR TITLE
Modernize deprecated CONNECTIVITY_ACTION in ConnectivityManager

### LINKED ISSUE #803: Modernize deprecated CONNECTIVITY_ACTION in ConnectivityManager (and bug fix on new methods)
The CONNECTIVITY_ACTION constant was deprecated in API level 28.
apps should use the more versatile [requestNetwork(NetworkRequest, PendingIntent)](https://developer.android.com/reference/android/net/ConnectivityManager#requestNetwork(android.net.NetworkRequest,%20android.app.PendingIntent)), [registerNetworkCallback(NetworkRequest, PendingIntent)](https://developer.android.com/reference/android/net/ConnectivityManager#registerNetworkCallback(android.net.NetworkRequest,%20android.app.PendingIntent)) or [registerDefaultNetworkCallback(NetworkCallback)](https://developer.android.com/reference/android/net/ConnectivityManager#registerDefaultNetworkCallback(android.net.ConnectivityManager.NetworkCallback)) functions instead for faster and more detailed updates about the network changes they care about.

## Location
https://github.com/Igalia/wolvic/pull/787/files#r1251796318

## Possible Solution
As suggested in:
- https://developer.android.com/reference/android/net/ConnectivityManager#CONNECTIVITY_ACTION

### PR DESCRIPTION
**Pull request by HollowMan6**
The CONNECTIVITY_ACTION constant was deprecated in API level 28. apps should use the more versatile requestNetwork(NetworkRequest, PendingIntent), registerNetworkCallback(NetworkRequest, PendingIntent) or registerDefaultNetworkCallback(NetworkCallback) functions instead for faster and more detailed updates about the network changes they care about.

Resolves #803

### CODE REVIEW

**Comment by HollowMan6** [comment]
> My main doubt about this change is that I think we're duplicating stuff. On the one hand we have the connectivityManager receiving broadcast events, and then we have the NetworkCallback object doing the same and trying to adapt to the legacy code.

> I'd remove this patch from the series and think carefully about what to do here.

Tried to get rid of connectivityManager but haven't had the luck of success. https://github.com/Igalia/wolvic/commit/cca41523be0cf286819b5b0cc3a23b78f224014c

**Comment by HollowMan6** [comment]
https://github.com/Igalia/wolvic/pull/906/commits/f7eec7d7f4c2617d8d261a520517d7d807df67b8
Interestingly, unlike the current main, we still need the null check here or wolvic will crash.

Reference to https://github.com/Igalia/wolvic/pull/908

**Comment by HollowMan6** [comment]
Now ready.

> > My main doubt about this change is that I think we're duplicating stuff. On the one hand we have the connectivityManager receiving broadcast events, and then we have the NetworkCallback object doing the same and trying to adapt to the legacy code.
> 
> > I'd remove this patch from the series and think carefully about what to do here.
> 
> Tried to get rid of connectivityManager but haven't had the luck of success. [cca4152](https://github.com/Igalia/wolvic/commit/cca41523be0cf286819b5b0cc3a23b78f224014c)

**Review by elima — APPROVED** [review]
LGTM.

I tested it by forcing a drop of the wifi (shutting down hotstop) and seems to work. Not sure if there is other ways of testing this.

**Pull request merged**
