### PR TITLE
Implement audio engine using Android Media Player

### LINKED ISSUE #1044: Implement an Android's MediaPlayer AudioEngine
We have an AudioEngine abstraction to play sounds on certain events like button clicks. However that AudioEngine is currently not implemented (it used to be implemented using Google's GVR in FxR).

It should be easy to implement it in terms of Android's `MediaPlayer`

### PR DESCRIPTION
**Pull request by HollowMan6**
Resolve #1044

- Set audio enabled by default.
- Disable playing sound when click on language button in Settings, since we will update all the language options (radio button) during loading, and that will trigger the click sound already, so we don't need to trigger another sound here.
- Add an option to disable sound effects in settings.

com igalia wolvic-20231005-222748

I know it's weird to put a setting option that is related to sound into Display, but it should be the best place for now since we don't have any other proper place.

### CODE REVIEW

**Comment by HollowMan6** [comment]
I've experienced some random sound effects temporary cut-outs while testing this (although it's rare), not sure what's going on here since I didn't find any possible cause when I tried to debug, and it reminds me of that gecko bug in https://github.com/Igalia/wolvic/issues/598#issuecomment-1499440501 Not sure how everything is related here.

**Review by svillar — COMMENTED** [review]
I like the patch as it is, not asking for any change. However I'd like to wait a bit before merging it, because I do prefer not having any sound over hearing random noises from time to time.

**Comment by HollowMan6** [comment]
> because I do prefer not having any sound over hearing random noises from time to time.

You can in any case disable the sound effects in the settings.

**Comment by svillar** [comment]
> > because I do prefer not having any sound over hearing random noises from time to time.
> 
> You can in any case disable the sound effects in the settings.

Right, but we better not deploy something that we now is buggy (for whatever reason) specially when it is something that is not critical.

**Comment by HollowMan6** [comment]
> > > because I do prefer not having any sound over hearing random noises from time to time.
> > 
> > 
> > You can in any case disable the sound effects in the settings.
> 
> Right, but we better not deploy something that we now is buggy (for whatever reason) specially when it is something that is not critical.

Yeah, but I doubt if we are able to actually fix this, as I believe it's something related to https://bugzilla.mozilla.org/show_bug.cgi?id=1766545

**Comment by HollowMan6** [comment]
> > > > because I do prefer not having any sound over hearing random noises from time to time.
> > > 
> > > 
> > > You can in any case disable the sound effects in the settings.
> > 
> > 
> > Right, but we better not deploy something that we now is buggy (for whatever reason) specially when it is something that is not critical.
> 
> Yeah, but I doubt if we are able to actually fix this, as I believe it's something related to https://bugzilla.mozilla.org/show_bug.cgi?id=1766545

Can confirm this to be caused by that bug as I can't reproduce the sound cut-off on my Android phone with no API

**Comment by svillar** [comment]
Maybe we could enable for the chromium backend only in the meantime

**Comment by svillar** [comment]
> > Maybe we could enable for the chromium backend only in the meantime
> 
> Yeah, but can we actually know what backend we are using on the Android side? Didn't see any code related to this. And since I don't have access to chromium_aar, I can't help test that on the chromium side.

Well you can always check the flavour used in the build

**Comment by HollowMan6** [comment]
> > > Maybe we could enable for the chromium backend only in the meantime
> > 
> > 
> > Yeah, but can we actually know what backend we are using on the Android side? Didn't see any code related to this. And since I don't have access to chromium_aar, I can't help test that on the chromium side.
> 
> Well you can always check the flavour used in the build

Updated so that now the sound effect is only enabled by default/configurable in settings in the Chromium backend.

**Review by svillar — APPROVED** [review]
Yeah let's land this

**Pull request merged**
