### PR TITLE
Use versionCodeToDate again in Settings dialog

### LINKED ISSUE #977: Restore the FxR inherited versionCode auto generation
Long time ago we decided not to use the automatically generated version codes that FxR used to build from the current date and manually specify our owns. We thought that could give us more control over the packages we generate. The thing is that it does not really help, and what's worst, it makes the process of uploading to stores more complex, because you must always upload higher and higher versionCode numbers.

I think it's time to go back to the automatically generated version codes again.

Note that the version code is shown in the settings, so PR #310 should be re-examined

Also see [this commit](https://github.com/Igalia/wolvic/commit/cad2d654781e491c9b42da0048895a6ea8d9af23)

### PR DESCRIPTION
**Pull request by HollowMan6**
This reverts commit 5c241fe2cb24db986c6792fcff2b6c9ce7731570 and cad2d654781e491c9b42da0048895a6ea8d9af23.

Resolves #977

com igalia wolvic-20230916-235628

### CODE REVIEW

**Review by svillar — CHANGES_REQUESTED** [review]
The idea indeed was kind of "revert" previous changes but not literally. We are not using taskcluster at all (Mozilla infra) so we shouldn't have any reference to that. Also my idea was to always use that new versioning system if possible not only on special builds.

**Comment by HollowMan6** [comment]
> The idea indeed was kind of "revert" previous changes but not literally. We are not using taskcluster at all (Mozilla infra) so we shouldn't have any reference to that.

Done.

> Also my idea was to always use that new versioning system if possible not only on special builds.

A heads-up that every build now seems to be a complete fresh rebuild and it takes a lot of time, and there's a comment in the original code:

> For local debug builds we use a fixed versionCode to not mess with the caching mechanism of the build system. The fixed local build number is 1.

**Comment by HollowMan6** [comment]
> > Also my idea was to always use that new versioning system if possible not only on special builds.
> 
> A heads-up that every build now seems to be a complete fresh rebuild and it takes a lot of time (troubles debug a lot), and there's a comment in the original code:
> 
> > For local debug builds we use a fixed versionCode to not mess with the caching mechanism of the build system. The fixed local build number is 1.

So My suggestion is that we revert to https://github.com/Igalia/wolvic/commit/a641ab423468e9ca9550cf5e43eefe99f4b65393 and still use the flag for the dynamic version code.

**Comment by HollowMan6** [comment]
Close this for now. Feel free to re-open if anyone wants to continue working on this.

**Pull request closed without merging**
