### PR TITLE
[VisionGlass] Fix pointer (aim) orientation

### LINKED ISSUE #1341: [VisionGlass] Calibration breaks pointer behaviour
The process of calibrating the pointer properly makes it point to the right direction, however it has some issues:
1. it adds flickering to the pointer in some positions
2. sometimes the x axis is inverted
3. pointer is lost for some time until it comes back

### PR DESCRIPTION
**Pull request by svillar**
This PR addresses the issues observed in the orientation of the aim (pointer). Among others:
1. pointer was not usable in multiwindow environment
2. pointer sometimes started to flicker
3. sometimes x axis got inverted

Fixes #1341

### CODE REVIEW

**Review by javifernandez — APPROVED** [review]

**Review by javifernandez — CHANGES_REQUESTED** [review]
Umm, the pointer doesn't work well in a multi-window context.

**Review by javifernandez — APPROVED** [review]
The behavior in a multi-window context is much better now, although there are still differences with the initial window (moving vertically is slower in the new window.)

The change in the code looks good and it's definitively a step in the right direction, so lets merge it now. We can investigate later the source of the differences and possible improvements, if needed.

**Review by felipeerias — APPROVED** [review]
LGTM. This implementation works significantly better than before.

**Comment by svillar** [comment]
> The behavior in a multi-window context is much better now, although there are still differences with the initial window (moving vertically is slower in the new window.)
> 
> The change in the code looks good and it's definitively a step in the right direction, so lets merge it now. We can investigate later the source of the differences and possible improvements, if needed.

Yes I'm aware of that. The problem is that the data we get from the phone is not accurate enough and starts to accumulate errors as you rotate on the Y axis. That's apparently a well known issue for phones (they don't really require that level of accuracy). There are proposals to combine sensor data to improve accuracy (although our current approach already combines accelerometer and gyroscope data) so we could make it better indeed.

**Pull request merged**
