### PR TITLE
[OpenXR] Restore the Khronos simple interaction profile

### LINKED ISSUE #1611: Doesn't detect controller on quest 3s
## Configuration

Wolvic version: current latest version in meta store
Wolvic build ID: 

Hardware: quest 3s

## Steps to Reproduce

1.opening wolvic
2.use controller
3.switfhing to hand tracking with the double tap on controller

## Current Behavior
 detect only hand tracking but fail to detect the controllers.

## Expected Behavior
 it should detect the controllers instead

## Error Logs and Stack Traces

<details open>

```
```

</details>

### PR DESCRIPTION
**Pull request by svillar**
It is no longer causing issues in Meta devices (at least in v69) so we should reenable it to improve compatibility with future or unsupported devices.

Fixes #1611

### CODE REVIEW

**Comment by svillar** [comment]
One of the things we need to test **for every device we support** is to remove the device line at https://github.com/Igalia/wolvic/blob/main/app/src/main/cpp/DeviceUtils.cpp#L132 so that is detected as unknown device. The controllers should still work, a different 3D model will be shown and only menu and trigger buttons will work.

**Review by felipeerias — CHANGES_REQUESTED** [review]
It works as expected on PICO 4 and Meta Quest 2.

Screenshot_com igalia wolvic dev_2024 11 18-22 13 37 306_317

com igalia wolvic dev-20241118-220250

However, I could not get it to work on HVR. Is that expected?

**Comment by javifernandez** [comment]
I have tested it on the following devices:
 - Quest2 / SO 71 -> BAD
 - Quest3 / SO 69 -> GOOD
 - Pico4 / SO 5.11.2 S -> GOOD

**Comment by svillar** [comment]
> However, I could not get it to work on HVR. Is that expected?

Very likely the HVR runtime does not support that profile. I'll check the logs

**Review by felipeerias — APPROVED** [review]
Thanks for checking. From my point of view, this works well on PICO and Meta (v72).

**Pull request merged**
