### PR TITLE
Don't reduce the size of the window in fullscreen

### PR DESCRIPTION
**Pull request by felipeerias**
Update the calculation of the window's current scale to match our resizing logic, so we can prevent making the window smaller when entering fullscreen.

Fixes https://github.com/Igalia/wolvic/issues/1486

### CODE REVIEW

**Comment by svillar** [comment]
OK so I'm interested in knowing how the behaviour would be from now on. Would it be possible to write down here the how the size calculation changes depending on the scenario?

**Comment by svillar** [comment]
BTW it works great :smile:

**Comment by felipeerias** [comment]
@svillar The calculation for resizing is roughly like this:

- we have defined the default, minimum, and maximum sizes for the window
- when we want to resize a window, we begin by identifying its main axis (horizontal or vertical)
- the scale will determine the size the main axis of the window: 1X is the default, MIN_SCALE is the minimum and MAX_SCALE is the maximum; other values are interpolated between those points 
- the cross axis is calculated so that the dimensions of the window match the desired aspect ratio
- there are additional checks so the result fits within the minimum and maximum sizes that we have defined 

This calculation is only done when we use a pre-defined scale, for example when using the resize buttons, not when the user resizes the window manually.

This PR walks that calculation backwards to find the current scale of the window, so we can prevent making it smaller when it goes to fullscreen.

**Review by svillar — APPROVED** [review]
Works nicely and I have no additional comments WRT the code, so let's merge it.

**Review by javifernandez — COMMENTED** [review]
The code looks good, indeed and it works well. 

However, do you think this code is very similar to the one that implements the resizeByMultiplier function ?   

I think some refactoring would make the resizing logic clearer.

**Pull request merged**
