### PR TITLE
Add option to clear all user data

### LINKED ISSUE #345: on a shared device clearing cache and history it does not reset everything
If you have a shared vr device (for demonstrations) and you want to reset it for the next user.

 Clearing cache and history does not seem to reset everything.

You also have to click don't reopen open tabs.

But even then if you browse pages it still has advertising suggestions for the last person that used possibly because  it remembers the last persons advertising ID
 
The only way I have found that resets everything is to uninstall and reinstall the app.

Could the clear cache and cookies be improved to clear everything similar to uninstall and reinstall?

## Configuration

the latest download as of Nov 18 on meta quest 2

Wolvic version: see above
Wolvic build ID: see above

Hardware: meta quest 2

## Steps to Reproduce

Browse to and web page and then another one
Clear cache and history and turn off reopen open tabs 
exit app 
Open app
Start typing a web page address anyone. Google search still seams to remember your last web pages and they appear at the top even though the delete cookies were pressed before closing the app .

1.
2.
3.

## Current Behavior

I would think clear cache and history would clear all data including ie advertising or tracking cookies but it doesn't seem too

If you clear cache and history it should behave like a fresh user and not show advertising for the last user due to saved cookies

## Possible Solution

Uninstall and reinstall is the current only solution.
It's not clear what needs to be reset without doing that

For shared kiosk virtual reality sets used at demonstrations so the next user gets a fresh clean start.

Add a better clean cookies and advertising I'd button

## Error Logs and Stack Traces

<details open>

```
```

</details>

### PR DESCRIPTION
**Pull request by HollowMan6**
This is available in settings, under Privacy & Security section.

When user choose the option, we will prompt user with detailed explanation of what's going to happen

resolve #345

com igalia wolvic-20230928-203918
com igalia wolvic-20230928-203927

### CODE REVIEW

**Review by svillar — CHANGES_REQUESTED** [review]
I like having this in the Settings but I don't think we need to add it to kiosk mode, after all, it's mean to be used to display a single experience per run.

**Comment by HollowMan6** [comment]
> I like having this in the Settings but I don't think we need to add it to kiosk mode, after all, it's mean to be used to display a single experience per run.

Okay, let's remove that in kiosk mode

**Comment by HollowMan6** [comment]
Done!

**Review by svillar — APPROVED** [review]
Thanks!

**Pull request merged**
