### PR TITLE
Batch updateWidget native calls

### LINKED ISSUE #448: [Pico] Swapchain limit hit when entering/leaving fullscreen videos
## Configuration

Hardware: Pico4 and Pico4E

## Steps to Reproduce

1. Open 3 windows
2. Open the aviation 360º video from the top of the start page in fullscreen
3. Exit fullscreen
4. Repeat the Enter/Exit fullscreen 3-4 times

## Current Behavior

Wolvic crashes due to surpassing the maximum of 16 swapchains

## Expected Behavior

No crash

### PR DESCRIPTION
**Pull request by svillar**
Whenever Android asks us to update some widget we queue a native task to perform
 the update in the native thread. Those tasks are not cancellable. So far so good. The 
thing is that sometimes we get several update widget requests in a short period of time.
The downside is that it involves expensive cycles of creation&destruction of swapchains,
for those widgets backed up by layers. This might cause peaks in the number of active
swapchain something that could be problematic (Pico for example).

That's why we're enqueuing those updateWidget() calls before calling the native methods.
We keep a hashtable with widget handles and the new widget placement. After 250ms we
go through that hash table and call the native methods. Any updateWidget call that happens
during the 250ms budget will replace the previous one, and thus, saving updates.

Fixes #448

### CODE REVIEW

**Comment by felipeerias** [comment]
@svillar  You are accidentally scheduling a new task every time that `enqueueUpdateWidgetNativeCall()` is called.

This could be one way to fix that:

```java
private Hashtable<Integer, WidgetPlacement> mPendingNativeWidgetUpdates = new Hashtable<>();
private ScheduledThreadPoolExecutor mPendingNativeWidgetUpdatesExecutor = new ScheduledThreadPoolExecutor(1);
private ScheduledFuture<?> mNativeWidgetUpdatesTask = null;

...

private void enqueueUpdateWidgetNativeCall(int handle, WidgetPlacement placement) {
    mPendingNativeWidgetUpdates.put(handle, placement);

    if (mNativeWidgetUpdatesTask == null || mNativeWidgetUpdatesTask.isDone()) {
        mNativeWidgetUpdatesTask = mPendingNativeWidgetUpdatesExecutor.schedule(() -> {
            for (Map.Entry<Integer, WidgetPlacement> entry : mPendingNativeWidgetUpdates.entrySet()) {
                queueRunnable(() -> updateWidgetNative(entry.getKey(), entry.getValue()));
            }
            mPendingNativeWidgetUpdates.clear();
        }, 250, TimeUnit.MILLISECONDS);
    }
}
```

Another question: is there a downside to having a delay of 250 milliseconds? Could it be shorter?

Testing in the Oculus with a delay of 250ms, I have seen up to 10 elements in `mPendingNativeWidgetUpdates` before the timer goes off.

**Comment by svillar** [comment]
> @svillar You are accidentally scheduling a new task every time that `enqueueUpdateWidgetNativeCall()` is called.
> 
> This could be one way to fix that:
> 
> ```java
> private Hashtable<Integer, WidgetPlacement> mPendingNativeWidgetUpdates = new Hashtable<>();
> private ScheduledThreadPoolExecutor mPendingNativeWidgetUpdatesExecutor = new ScheduledThreadPoolExecutor(1);
> private ScheduledFuture<?> mNativeWidgetUpdatesTask = null;
> 
> ...
> 
> private void enqueueUpdateWidgetNativeCall(int handle, WidgetPlacement placement) {
>     mPendingNativeWidgetUpdates.put(handle, placement);
> 
>     if (mNativeWidgetUpdatesTask == null || mNativeWidgetUpdatesTask.isDone()) {
>         mNativeWidgetUpdatesTask = mPendingNativeWidgetUpdatesExecutor.schedule(() -> {
>             for (Map.Entry<Integer, WidgetPlacement> entry : mPendingNativeWidgetUpdates.entrySet()) {
>                 queueRunnable(() -> updateWidgetNative(entry.getKey(), entry.getValue()));
>             }
>             mPendingNativeWidgetUpdates.clear();
>         }, 250, TimeUnit.MILLISECONDS);
>     }
> }
> ```
> 
> Another question: is there a downside to having a delay of 250 milliseconds? Could it be shorter?
> 
> Testing in the Oculus with a delay of 250ms, I have seen up to 10 elements in `mPendingNativeWidgetUpdates` before the timer goes off.

Oh indeed, I'm stupid :smile: . Since it's a completely different approach, mind uploading a new PR with your proposed solution?

WRT to 250ms maybe indeed it's too much, but in my testing 100ms for example was not enough. But perhaps it's just because the timer thing was completely wrong.

**Comment by felipeerias** [comment]
@svillar  I have opened PR https://github.com/Igalia/wolvic/pull/454 with the suggested implementation.

**Comment by svillar** [comment]
Let's close this then

**Pull request closed without merging**
