### PR TITLE
[Vision Glass] Dynamic realign button

### PR DESCRIPTION
**Pull request by felipeerias**
Add a button to realign the controller and the view.

This button displays a dynamic view of the controller's position in order to better communicate its purpose.

The circle in the button tracks the controller position, tapping the button will reset that position and place the circle in the middle again.
This functionality is not implemented in this PR.

### CODE REVIEW

**Comment by felipeerias** [comment]
This is how the button looks like while in use:

https://github.com/Igalia/wolvic/assets/1412060/c16df57d-f023-418b-b29d-e99ed88393a4

**Comment by svillar** [comment]
I've uploaded #1310 providing API to perform the calibration. You'd just have to add something like
```
+        mBinding.realignButton.setOnClickListener(v -> {
+            queueRunnable(() -> calibrateController());
+        });
```
to the UI setup code to perform the calibration when clicking on the realign button.

**Comment by felipeerias** [comment]
Thank you @svillar, I've updated this PR to use the functionality introduced in https://github.com/Igalia/wolvic/pull/1310

**Review by svillar — APPROVED** [review]
LGTM

**Pull request merged**
