### PR TITLE
(WIP) Improve error handling for Speech Recognition 

### PR DESCRIPTION
**Pull request by jekirl**
There are currently a few problems with the way the speech recognition works in main:

* Any error for speech recognition instantly starts a new speech recognition request -- this has the very adverse effect of basically DDoSing any cloud ASR service if it is having network issues. 
  * Fix: This is fixed by removed the `startVoiceSearch();`, it could be replaced with a version that is debounced but for now I removed it.
* There are not enough error types
  * Fix: More error types have been added, however they need to be implemented in the actual recognition service and supported by the UI.
* Locale support is not checked.
  * Temp Fix:  I have added a supportsASR to the interface. For now this will only be checked when the actual voice widget starts, however it would probably be better to disable the mic button all together if the language is not supported. 

I am marking this PR WIP for a two reasons, however fixing the infinite restart on failure likely means that this is still worth merging even without the future work
- Needs testing on all platforms still.
- Needs localization of error strings.
- (potentially future work) The voice search language selection in settings should be aware of what languages are supported, currently there is tech debt from the Mozilla implementation. I believe a better settings UX in general is required to give the user the ability to understand (a) what speech recognition is being used, (b) if the current device language _is_ supported or not, and (c) what languages are supported.

### CODE REVIEW

**Comment by MortimerGoro** [comment]
Instead of disabling the microphone button for a not supported locale, one alternative is having a different subset of languages for voice recognition: e.g. I might have the UI in spanish, but as I also know english I can use the voice search in English.

In order to do that we'd need a querySupportedLanguages in the interface. HVRSpeechRecognizer also supports that API so it can be implemented in both supported recognizers right now. With that list we can change the Settings->Voice Language UI, adapting the list of languages to the supported languages by the ASR.

**Comment by MortimerGoro** [comment]
As a follow up feature/shortcut could also add a dropdown of language in the voice search UI

**Comment by jekirl** [comment]
If it is OK with you @MortimerGoro I think merging in this first and then a second PR to do the UI/settings changes might be best. The retry behavior on master right now is very undesirable. 

My caution on rushing is that there really needs to be some cleanup in a few spots in the code base of locale vs language. More specifically, the fallback mechanism for how Mozilla dealt with locale -> language fallback should be removed and made a responsibility of each speech recognizer rather than at the settings/widget level. 
- For the MK speech recognizer we do this on backend (i.e. we support es-MX and es-ES, but if someone sends us es-CO we use the es-MX model instead). I do not think anything would need to change on our end since we are pretty tolerant of poorly formed locales.
- The HW speech recognizer requires exact locale match I believe. To fix this we would need to wrap it and convert to nearest supported locale before starting the ASR (i.e. map es-MX -> es-ES) 

Happy to take on the above as a follow up PR.

**Review by MortimerGoro — APPROVED** [review]

**Comment by MortimerGoro** [comment]
Sounds good, I've been testing the current patch and LGTM.

We can do the second part as a follow up PR

**Pull request merged**
