### PR TITLE
Enable word auto complete for Latin keyboards

### PR DESCRIPTION
**Pull request by HollowMan6**
Inspiration from Chinese/Japanese candidates input.

Wordlist databases taken from
https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/refs/heads/main/dictionaries/

Script for converting from text format wordlist into sqlite3 databases:
https://gist.github.com/HollowMan6/e4bb09cd9cf6d6cc895c24659c015d06

https://github.com/Igalia/wolvic/assets/43995067/27d45cc6-6045-4d4b-9009-5a3236853321

image

Resolve https://github.com/Igalia/wolvic/issues/737

### CODE REVIEW

**Comment by svillar** [comment]
This is really cool. I have two questions:
* why allowing users to disable this? Everything runs locally so there should be no privacy concerns. Also it isn't intrusive as mobile phone keyboards that autocomplete/replace what you type. I think we should have it always on
* what's the license of the wordlists you're using? Can we redistribute them?

**Review by svillar — COMMENTED** [review]
This is really cool. I have two questions:

* why allowing users to disable this? Everything runs locally so there should be no privacy concerns. Also it isn't intrusive as mobile phone keyboards that autocomplete/replace what you type. I think we should have it always on
* what's the license of the wordlists you're using? Can we redistribute them?

**Comment by HollowMan6** [comment]
> * why allowing users to disable this? Everything runs locally so there should be no privacy concerns. Also it isn't intrusive as mobile phone keyboards that autocomplete/replace what you type. I think we should have it always on

Ok, reasonable, I dropped the last commit: https://github.com/Igalia/wolvic/pull/1104/commits/168ae4138fc9a78ff2c79237477fd4f89ff85809

> * what's the license of the wordlists you're using? Can we redistribute them?

It's from the AOSP and the license is Apache-2.0 https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/refs/heads/main/NOTICE So it should be fine.

**Review by svillar — APPROVED** [review]
So the patch is great, and works like a charm so I'm integrating it.

That said this is not ready to be released because doing that would involve increasing the package size in ~50Mb something that we better not do (I guess, although connections are better and faster now, I think that we need a good first experience).

I think we need a way to download them on demand.

**Comment by HollowMan6** [comment]
> I think we need a way to download them on demand.

Yes, that's reasonable. Added to my to-do list.

**Pull request merged**
