### PR TITLE
Translated using Weblate (Galician) 

### PR DESCRIPTION
**Pull request by felipeerias**
Translation: Wolvic/Wolvic
Translate-URL: https://hosted.weblate.org/projects/wolvic/wolvic/gl/

### CODE REVIEW

**Review by svillar — APPROVED** [review]
Obrigado!

**Comment by svillar** [comment]
There seems to be merging issues with this translation

**Comment by felipeerias** [comment]
@svillar What problems are you seeing?

The translations file is the same as in the `l10n-weblate` branch except for one duplicated entry.

**Comment by svillar** [comment]
> @svillar What problems are you seeing?
> 
> The translations file is the same as in the `l10n-weblate` branch except for one duplicated entry.

It was the github UI the one complaining and preventing us from merging :shrug:

**Pull request merged**
