### PR TITLE
Prevent windows out of reach

### PR DESCRIPTION
**Pull request by felipeerias**
Disable head lock if window movement is enabled, and viceversa, otherwise the windows might be moved out of the user's reach.

### CODE REVIEW

**Comment by felipeerias** [comment]
This branch needs to be rebased after https://github.com/Igalia/wolvic/pull/1124 and https://github.com/Igalia/wolvic/pull/1050 are merged.

The commit that implements this change is https://github.com/Igalia/wolvic/pull/1125/commits/73f36958a182d4171ba0690182b459e02254245d

**Comment by svillar** [comment]
This should not be needed if we do what I mentioned here https://github.com/Igalia/wolvic/pull/1050#pullrequestreview-1757824018

**Comment by HollowMan6** [comment]
> The commit that implements this change is [73f3695](https://github.com/Igalia/wolvic/commit/73f36958a182d4171ba0690182b459e02254245d)

I have rebased #1050 with head lock, and land the commit into that PR.

> This should not be needed if we do what I mentioned here https://github.com/Igalia/wolvic/pull/1050#pullrequestreview-1757824018

I guess it's not easy to do so https://github.com/Igalia/wolvic/pull/1050#issuecomment-1834467042 It can be a temporary solution until any of you figure that out.

**Comment by felipeerias** [comment]
Included in https://github.com/Igalia/wolvic/pull/1050

**Pull request closed without merging**
