### PR TITLE
Add translations from Weblate (Danish)

### PR DESCRIPTION
**Pull request by elima**
This PR is an end-to-end test of the new translation process we are setting up for Wolvic using [Weblate](https://weblate.org/).

The strings should have been reviewed already by approved reviewers on Weblate. But as a side note, it is still not completely clear to me whether we should defer the review to the PR, which we have to open anyway to merge into `main` branch; and remove the requirement of review on Weblate side. Reviewing twice seems like unnecessary overhead.

### CODE REVIEW

**Comment by elima** [comment]
All the removed blanks lines in the diff come from a hook in Weblate which "normalizes" the xml file. It should happen only once, the first time an xml file is touched by Weblate.

**Comment by svillar** [comment]
> All the removed blanks lines in the diff come from a hook in Weblate which "normalizes" the xml file. It should happen only once, the first time an xml file is touched by Weblate.

Can we get rid of that normalization hook? I understand it'll only happen once, but it completely breaks the history of the file

**Comment by elima** [comment]
I will look into removing the hook, but this is a hosted version, not sure we have that option.

**Comment by elima** [comment]
@svillar, after looking in the docs, it seems it is not trivial to keep the original format of the translations files:

From the [Weblate docs](https://docs.weblate.org/en/latest/faq.html?highlight=disable%20hook#does-weblate-update-translation-files-besides-translations):

```
Does Weblate update translation files besides translations?

Weblate tries to limit changes in translation files to a minimum. For some file formats it might unfortunately lead to reformatting the file. If you want to keep the file formatted your way, please use a pre-commit hook for that.
```

The problem is that we don't have the option from the web UI to add a pre-commit hook. But even if we had it, it will reformat the file our way *after* it has been modified by Weblate hooks. So all in all, we could try to add the blank lines back it won't prevent changes made by hand to be overwritten by our pre-commit hook script.

Is it really important to keep the translation files history? Can't we just call FxR translation file format *the past* and move on to our new format without blank lines? :)

**Comment by svillar** [comment]
> @svillar, after looking in the docs, it seems it is not trivial to keep the original format of the translation files:
> 
> From the [Weblate docs](https://docs.weblate.org/en/latest/faq.html?highlight=disable%20hook#does-weblate-update-translation-files-besides-translations):
> 
> ```
> Does Weblate update translation files besides translations?
> 
> Weblate tries to limit changes in translation files to a minimum. For some file formats it might unfortunately lead to reformatting the file. If you want to keep the file formatted your way, please use a pre-commit hook for that.
> ```
> 
> The problem is that we don't have the option from the web UI to add a pre-commit hook. But even if we had it, it will reformat the file our way _after_ it has been modified by Weblate hooks. So all in all, we could try to add the blank lines back but it won't prevent changes made by hand to be overwritten by our pre-commit hook script.
> 
> Is it really important to keep the translation files history? Can't we just call FxR translation file format _the past_ and move on to our new format without blank lines? :)

Yeah, I'm fine. I was just having doubts because it seems a very specific requirement of a very specific tool.

The only doubt I have is, is this ready to be merged or just a test?

**Comment by elima** [comment]
It is a legit PR. I'm testing the workflow from translating in Weblate to merging the resulting commits to `main`. This commit includes some translations to Danish that were missing (I volunteered for that language).

Right now this is the only manual step we have, opening and merging the PRs. I think it is important to keep this manual for now, because we have the chance of including/excluding particular commits coming from Weblate, for example grouping commits by language, to have the corresponding volunteer for that language review that PR alone, without potential commits for other languages.

In the future we could look into having Weblate (or other tool) open the PRs for us, but I would start with caution.

**Pull request merged**
