### PR TITLE
[l10n] Update translations to Swedish

### PR DESCRIPTION
**Pull request by elima**
Via Weblate. Currently translated at 100% (651 of 651 strings).

Thanks, @bittin!

### CODE REVIEW

**Comment by elima** [comment]
@matlu, maybe you can help us review this PR with Swedish translations? Please, let me know if you need help :)

Thanks a bunch!

**Comment by bittin** [comment]
Swedish translation is done now, but yeah some review would be great @matlu @elima

**Comment by bittin** [comment]
@elima no problem :) great

**Comment by bittin** [comment]
@matlu ping

**Comment by bittin** [comment]
and translated some more strings now

**Comment by elima** [comment]
> and translated some more strings now

Super! Just added them to the PR branch.

I'm looking for other reviewers.

Thanks!

**Review by svillar — APPROVED** [review]
Wow thanks

**Comment by bittin** [comment]
and Swedish updated again

**Pull request merged**
