### PR TITLE
Define the "mainlandChina" store flavour

### PR DESCRIPTION
**Pull request by felipeerias**
This PR defines the "mainlandChina" store flavour, which includes a specific phone UI.

### CODE REVIEW

**Review by javifernandez — APPROVED** [review]
lgtm

**Comment by svillar** [comment]
Why?

We already have AppInChina for that

**Comment by javifernandez** [comment]
> @felipeerias @javifernandez Why?
> 
> We already have AppInChina for that

We didn't want to use the "AppInChina" name as part of the Wolvic code; not a special reason, but we thought something more generic was more appropriated.

**Comment by svillar** [comment]
> > @felipeerias @javifernandez Why?
> > We already have AppInChina for that
> 
> We didn't want to use the "AppInChina" name as part of the Wolvic code; not a special reason, but we thought something more generic was more appropriated.

So let me give a bit of context. In the past we had a "country" dimension. Its values where china and world. We used that to implement specifics for HVR in China. However that got replaced with the "store" dimension. The idea of the store dimension is to precisely specify specifics for stores. I admit you could consider that the adaptations for chinese market are a "country" adaptation but the idea was to have them as a "store" adaptation. That's why I used directly appInChina because that's exactly the store we are using. 

Note that this is totally transparent for users anyway as this is a build configuration stuff.

**Pull request merged**
