### PR TITLE
Move Bookmarks and Downloads to the tray 

### PR DESCRIPTION
**Pull request by felipeerias**
For convenience, replace the Library button with separate buttons for the Bookmarks and Downloads. This is the first step in reorganizing the Library and Tray.

Simplify the code to animate the buttons' padding when selected.

### CODE REVIEW

**Comment by felipeerias** [comment]
This PR depends on https://github.com/Igalia/wolvic/pull/1644

**Review by svillar — COMMENTED** [review]
The code looks good. However my question is, isn't it a bit weird to have to click on the downloads button for example to access the history?

**Comment by jennie-bell** [comment]
I thought so too! I had imagined a better use of the tray while reading through the Future UI Evolution, like centering and replacing the private browsing button with a kebab or chocolate icon that temporarily expands the tray to a few more buttons, separating all the library buttons, and maybe decluttering the taskbar.

**Comment by felipeerias** [comment]
@svillar  The idea with the reorganisation of the library is to make each section easier to reach. Currently the library holds together a bunch of things that are not necessarily related to each other. 

What I am thinking at the moment is the following:

- one button in the tray for Bookmarks and History
- one button in the tray for Downloads
- Add-ons are currently reachable through the right-side menu, maybe it makes sense to also add a link to them in the Settings?
- Web Apps are not very useful right now, but my plan is to include them in the New Tab that we are working on.

**Comment by svillar** [comment]
> @svillar The idea with the reorganisation of the library is to make each section easier to reach. Currently the library holds together a bunch of things that are not necessarily related to each other.
> 
> What I am thinking at the moment is the following:
> 
>     * one button in the tray for Bookmarks and History
> 
>     * one button in the tray for Downloads
> 
>     * Add-ons are currently reachable through the right-side menu, maybe it makes sense to also add a link to them in the Settings?
> 
>     * Web Apps are not very useful right now, but my plan is to include them in the New Tab that we are working on.

Sure but I am not sure that adding more buttons is the way to go necesarily, mainly because it clutters the UI a lot. Also things like history won't be reachable directly (you'd have to go to downloads and then switch to history which is much more cumbersome than having a single button for library).

**Comment by felipeerias** [comment]
The idea is that History will be reachable from Bookmarks, which I think makes sense. It is what mobile Safari does, for example.

Having separate buttons for Downloads and Bookmarks/History is done by other browsers as well.

Basically my point is that the "Library" gathers together a bunch of stuff that is not all related and it makes the UI a bit more complex than it needs to be.

As a first step, my suggestion is to add the items that I detailed above but keep the side navigation when you are on one of the sections, and then we evaluate the next steps.

**Review by svillar — APPROVED** [review]
OK you have convinced me. Let's merge this then

**Pull request merged**
