### PR TITLE
Remove version check activity

### PR DESCRIPTION
**Pull request by svillar**
We're removing the version check activity for a couple of reasons:
1. seems to be the cause (or at least unveil) weird playback issues (see issue #1610)
2. it isn't really needed
   * 2.1 meta has its own checks in the store
   * 2.2 pico check was for very old versions of the OS, so in practice there is no much difference 

Apart from that it's much simpler to have just 1 activity than 2

### CODE REVIEW

**Review by javifernandez — APPROVED** [review]
I agree with the revert, but we should evaluate whether we can integrate later some of the changes these 4 commits provided (eg removal of the spheres hands model)

**Comment by svillar** [comment]
> I agree with the revert, but we should evaluate whether we can integrate later some of the changes these 4 commits provided (eg removal of the spheres hands model)

we definitely not want to bring the spheres models back

**Comment by MatthewHallCom** [comment]
Any update on this making it into a tagged release? We're seeing this cause breaking issues with recent Meta Quest OS versions

**Comment by svillar** [comment]
> Any update on this making it into a tagged release? We're seeing this cause breaking issues with recent Meta Quest OS versions

The next release, likely in January will have this PR for sure

**Comment by EasonZxp** [comment]
"Can we confirm that reverting this change fixes the issue 'No video playback unless I mute the video #1610'? I compiled a new Wolvic APK to test on Quest3 and found that the problem still persists. However, the official release APK does not have this issue. I'm not sure where the difference lies. What is certain is that I had already reverted this change when I compiled."

**Comment by svillar** [comment]
> "Can we confirm that reverting this change fixes the issue 'No video playback unless I mute the video #1610'? I compiled a new Wolvic APK to test on Quest3 and found that the problem still persists. However, the official release APK does not have this issue. I'm not sure where the difference lies. What is certain is that I had already reverted this change when I compiled."

The official Meta release does indeed have some extra changes. We didn't do an official new release after 1.7.1 because it takes a lot of time, but we upgraded the Meta package. Check the https://github.com/Igalia/wolvic/tree/release/1.7.1-meta branch for additional context

**Comment by svillar** [comment]
Oh, and for the Quest3S there are also additional fixes in release/1.7.1-quest3S branch as well. Meta added some OpenXR runtime changes (basically removed some features without prior notice) that made Wolvic crash with the newer OS releases

**Pull request merged**
